-- Changes made in the DB:
-- #2
DROP TABLE arrg_ROLLOFF;
ALTER TABLE arrg_PULL_LIST ADD`timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
-- #3
ALTER TABLE arrg_STAGING ADD `cb_labels` INT(3);


-- create new tables.
CREATE TABLE `arrg_PULL_LIST`(
	`site` VARCHAR(30) NOT NULL,
	`tag` VARCHAR(7) NOT NULL PRIMARY KEY,
	`room` VARCHAR(30) NOT NULL,
	`model` VARCHAR(30) NOT NULL,
	`status` VARCHAR(30),
	`roll_off` VARCHAR(30),
	`timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT COLLATE utf8_unicode_ci;

CREATE TABLE `arrg_MOVES`(
	`id` INT(10) AUTO_INCREMENT NOT NULL  PRIMARY KEY,
	`site` VARCHAR(30)NOT NULL,
	`tag` VARCHAR(7) NOT NULL,
	`old_room` VARCHAR(30),
	`new_room` VARCHAR(30),
	`device_type` VARCHAR(2) NOT NULL,
	`status` VARCHAR(30)
)DEFAULT COLLATE utf8_unicode_ci;

CREATE TABLE `arrg_PLACEMENT`(
	`id` INT(10) AUTO_INCREMENT NOT NULL  PRIMARY KEY,
	`site` VARCHAR(30) NOT NULL,
	`room` VARCHAR(30) NOT NULL,
	`device_type` VARCHAR(2) NOT NULL,
	`tag` VARCHAR(7)
)DEFAULT COLLATE utf8_unicode_ci;

CREATE TABLE `arrg_STAGING`(
	`id` INT(2) AUTO_INCREMENT NOT NULL  PRIMARY KEY,
	`site` VARCHAR(30),
	`cb_incoming` INT(3),
	`lt_incoming` INT(3),
	`dt_incoming` INT(3),
	`cb_labels` INT(3),
	`cb_delivered` INT(3),
	`lt_delivered` INT(3),
	`dt_delivered` INT(3),
	`cb_unboxed` INT(3),
	`lt_unboxed` INT(3),
	`dt_unboxed` INT(3),
	`cb_setup` INT(3),
	`lt_setup` INT(3),
	`dt_setup` INT(3)
)DEFAULT COLLATE utf8_unicode_ci;

/*insert dummy data into the tables*/

INSERT INTO arrg_MOVES
	(`site`,`tag`,`old_room`,`new_room`,`device_type`,`status`)
VALUES
	('Crestview', '99YKRM1','100','201','dt',NULL),
	('Crestview', 'H40LRM1','100','201','dt',NULL),
	('Crestview', 'FMXKRM1','231','123','dt',NULL),
	('Davidson', 'C9YKRM1','3','1','ct','moved'),
	('Crestview', '99YRRM1','100','201','dt',NULL)
;

INSERT INTO `arrg_STAGING` VALUES
	('1','Crestview','175','58','62','175','175','58','62','175','58','62','175','58','62'),
	('2','Antioch','50','32','24','50','50','32','24',NULL,NULL,NULL,NULL,NULL,NULL),
	('3','Bob Sikes','50','32','24',NULL,'50','32','24',NULL,NULL,NULL,NULL,NULL,NULL),
	('4','Davidson','100','21','17','100','100','21','17',NULL,NULL,NULL,NULL,NULL,NULL)
;

INSERT INTO arrg_PULL_LIST VALUES ('Crestview','340BQM1','103','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','59H9QM1','103','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C40BQM1','103','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','5BH9QM1','105','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','9J2BQM1','105','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','39H9QM1','113','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','550BQM1','113','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','740BQM1','113','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','82Q9QM1','113','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C30BQM1','117','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D30BQM1','117','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D8H9QM1','117','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FBH9QM1','117','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','HJ2BQM1','117','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','JBH9QM1','141','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D9H9QM1','145','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','940BQM1','149','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','HBH9QM1','151','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','42Q9QM1','257','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G30BQM1','246-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','2CH9QM1','247','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','540BQM1','247','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FZLRSM1','342','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','HXLRSM1','601','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','1BH9QM1','344','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F9H9QM1','344','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FYLRSM1','361','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','4CH9QM1','402','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','HWLRSM1','405 - Interpreter Using','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J30BQM1','406','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','2BH9QM1','409','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B9H9QM1','409','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','1CH9QM1','410','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B8H9QM1','410','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','440BQM1','411','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','69H9QM1','411','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','930BQM1','411','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F30BQM1','411','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B30BQM1','412','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C8H9QM1','412','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D40BQM1','412','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GJ2BQM1','412','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','6BH9QM1','502','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DZLRSM1','506','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','22Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','250BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','31Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','3CH9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','49H9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','4BH9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','52Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','5CH9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','660BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','730BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','73Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','7BH9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','830BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','840BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','850BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','91Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','950BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B1Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B3Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B40BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B50BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','BJ2BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C50BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CJ2BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CVS9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F2Q9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FJ2BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H50BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J50BQM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J9H9QM1','511-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','9BH9QM1','513','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','140BQM1','806-OFFICE','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','1K2BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','21Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','260BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','32Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','350BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','3BH9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','41Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','460BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','61Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','62Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','63Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','650BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','6J2BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','7J2BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','83Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','92Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','B2Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','BVS9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C9H9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D1Q9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D50BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DJ2BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F50BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F8H9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G50BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G8H9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G9H9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H40BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H8H9QM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','JJ2BQM1','813-Lab','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GYLRSM1','813-Lab Office','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GWLRSM1','820','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','240BQM1','821','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CXLRSM1','821','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CYLRSM1','821','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CZLRSM1','822','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DXLRSM1','822','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FXLRSM1','822','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GXLRSM1','822','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','79H9QM1','Circulation','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','89H9QM1','Girls Softball','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','11Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','12Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','13Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','150BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','160BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','19H9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','23Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','29H9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','33Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','360BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','43Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','450BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','51Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','53Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','560BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','6CH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','71Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','72Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','750BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','7CH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','81Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','8BH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','8CH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','8J2BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','93Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','99H9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','9VS9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','BBH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C1Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','C2Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','CBH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','D2Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DBH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DVS9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F1Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','F40BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','FVS9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G1Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G2Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','G40BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GBH9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','GVS9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H1Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H2Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H30BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','H9H9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J1Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J2Q9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J40BQM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','J8H9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','JPK9QM1','MC','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','640BQM1','Tech Office','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Crestview','DYLRSM1','Tech Office','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1J58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2J58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3H58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4G58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4J58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5H58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5J58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8G58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8K58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BF58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BK58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CC58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CH58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CJ58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DC58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FD58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FH58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GD58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HF58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HG58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HYLRSM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JJ58QM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JWLRSM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JYLRSM1','201LAB','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2F58QM1','301','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FC58QM1','302','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GC58QM1','304','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2G58QM1','308','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DF58QM1','308','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1K58QM1','310','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5D58QM1','401','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6D58QM1','401','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HJ58QM1','401','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JG58QM1','402','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3J58QM1','403','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FJ58QM1','403','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2H58QM1','404','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5K58QM1','404','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9H58QM1','404','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5G58QM1','407','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BCFW1N1','408','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BG58QM1','408','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1F58QM1','409','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4H58QM1','410','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JH58QM1','410','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FG58QM1','411','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4K58QM1','412','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7T6SBT1','501','Latitude E5420',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JD58QM1','501','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7H58QM1','505','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BD58QM1','505','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6K58QM1','508','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CD58QM1','508','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JC58QM1','508','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8F58QM1','509','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DJ58QM1','510','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DH58QM1','511','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4F58QM1','512','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6J58QM1','512','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HH58QM1','512','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','4D58QM1','603','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9G58QM1','603','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3K58QM1','604','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BH58QM1','604','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DG58QM1','604','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3D58QM1','605','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7K58QM1','605','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CG58QM1','605','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1H58QM1','607','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7F58QM1','607','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9F58QM1','607','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9K58QM1','608','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','CF58QM1','608','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','DD58QM1','608','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','JF58QM1','609','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1D58QM1','611','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6G58QM1','611','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','5F58QM1','702','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8D58QM1','706','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6H58QM1','801','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9J58QM1','801','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','1G58QM1','802','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7G58QM1','802','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8J58QM1','803','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2D58QM1','804','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','BJ58QM1','804','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GG58QM1','805','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3G58QM1','806','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','7J58QM1','806','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HD58QM1','806','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','2K58QM1','807','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','HC58QM1','807','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','3F58QM1','808','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GF58QM1','808','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GJ58QM1','808','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','FF58QM1','812','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','GH58QM1','812','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','6F58QM1','P704','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','8H58QM1','P704','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Antioch','9D58QM1','P704','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','26H9QM1','100','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','28H9QM1','201','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','38H9QM1','201','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','9H2BQM1','201','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','D6H9QM1','201','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','JH2BQM1','201','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','56H9QM1','205','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','17H9QM1','207','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','D7H9QM1','207','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','98H9QM1','300','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','16H9QM1','315','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','48H9QM1','315','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','C5H9QM1','315','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','97H9QM1','401','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','27H9QM1','403','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','46H9QM1','403','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','B7H9QM1','403','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','3J2BQM1','501','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','6H2BQM1','503','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','47H9QM1','512','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','4H2BQM1','513','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','J7H9QM1','513','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','5J2BQM1','514','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','D5H9QM1','514','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','1J2BQM1','515','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','H5H9QM1','601','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','F7H9QM1','603','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','B4MRSM1','605','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','G3MRSM1','605','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','7H2BQM1','606','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','8H2BQM1','606','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','5H2BQM1','609','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','2J2BQM1','613','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','36H9QM1','613','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','88H9QM1','614','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','B5H9QM1','700','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','96H9QM1','700','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','B6H9QM1','701','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','BH2BQM1','701','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','DH2BQM1','701','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','4J2BQM1','702','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','18H9QM1','703','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','86H9QM1','703','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','HH2BQM1','703','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','CH2BQM1','706','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','G5H9QM1','706','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','77H9QM1','707','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','C7H9QM1','708','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','GH2BQM1','709','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','H7H9QM1','507 - ISS','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','68H9QM1','CIRCULATION','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','J5H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','37H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','57H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','58H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','66H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','67H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','76H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','78H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','87H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','C6H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','F5H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','F6H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','FH2BQM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','G6H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','G7H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','H6H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Davidson','J6H9QM1','MC','Optiplex 780','Pulled',NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','270LRM1','10','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','450LRM1','10','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','DZ0LRM1','10','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','BVKKRM1','11','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','1Z0LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','201LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','260LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','2VKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','2Z0LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','3VKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','3Z0LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','4VKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','550LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','611LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','670LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','760LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','950LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','B50LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','D01LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','D50LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','F01LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','F60LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','FVKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','H60LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','HZ0LRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','JTKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','JVKKRM1','12LAB','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','501LRM1','15','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','H01LRM1','15','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','J01LRM1','15','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','9VKKRM1','16','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','CZ0LRM1','16','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','7VKKRM1','18','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','811LRM1','18','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','DVKKRM1','18','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','311LRM1','19','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','350LRM1','19','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','860LRM1','19','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','5Z0LRM1','23','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','C01LRM1','23','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','G01LRM1','23','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','711LRM1','24','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','960LRM1','24','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','D60LRM1','24','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','1WKKRM1','35','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','470LRM1','35','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','H50LRM1','35','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','8VKKRM1','36','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','B01LRM1','36','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','HVKKRM1','36','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','1VKKRM1','37','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','850LRM1','37','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','F50LRM1','37','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','601LRM1','38','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','6VKKRM1','38','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','C50LRM1','38','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','JZLRSM1','45','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','9Z0LRM1','46','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','C60LRM1','46','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','8Z0LRM1','57','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','170LRM1','6','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','4Z0LRM1','6','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','G60LRM1','6','Optiplex 780',NULL,NULL);
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','301LRM1','7','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','570LRM1','7','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','650LRM1','7','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','211LRM1','71','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','411LRM1','71','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','870LRM1','71','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','BZ0LRM1','71','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','160LRM1','8','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','6Z0LRM1','8','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','750LRM1','8','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','250LRM1','8','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','970LRM1','81','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','B60LRM1','13','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','801LRM1','82','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','CVKKRM1','82','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','FZ0LRM1','82','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','511LRM1','83','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','7Z0LRM1','83','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','JZ0LRM1','83','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','560LRM1','84','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','5VKKRM1','84','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','GVKKRM1','84','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','901LRM1','86','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','101LRM1','87','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','370LRM1','87','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','460LRM1','87','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','360LRM1','88','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','660LRM1','88','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','770LRM1','88','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','GZ0LRM1','88','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','401LRM1','9','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','J50LRM1','9','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','J60LRM1','9','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','701LRM1','CIRCULATION','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','111LRM1','MC','Optiplex 780','roll_off','Shoal River ');
INSERT INTO arrg_PULL_LIST VALUES ('Bob Sikes','G50LRM1','P6','Optiplex 780','roll_off','Shoal River ');

INSERT INTO arrg_PLACEMENT VALUES (1,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (2,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (3,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (4,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (5,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (6,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (7,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (8,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (9,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (10,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (11,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (12,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (13,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (14,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (15,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (16,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (17,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (18,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (19,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (20,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (21,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (22,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (23,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (24,'Antioch','119F-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (25,'Antioch','812','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (26,'Antioch','808','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (27,'Antioch','808','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (28,'Antioch','806','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (29,'Antioch','806','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (30,'Antioch','810','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (31,'Antioch','807','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (32,'Antioch','801','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (33,'Antioch','801','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (34,'Antioch','802','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (35,'Antioch','804','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (36,'Antioch','308','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (37,'Antioch','410','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (38,'Antioch','408','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (39,'Antioch','403','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (40,'Antioch','409','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (41,'Antioch','404','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (42,'Antioch','404','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (43,'Antioch','401','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (44,'Antioch','401','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (45,'Antioch','508','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (46,'Antioch','509','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (47,'Antioch','510','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (48,'Antioch','505','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (49,'Antioch','505','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (50,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (51,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (52,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (53,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (54,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (55,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (56,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (57,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (58,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (59,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (60,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (61,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (62,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (63,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (64,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (65,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (66,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (67,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (68,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (69,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (70,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (71,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (72,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (73,'Antioch','506-Lab','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (74,'Antioch','502','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (75,'Antioch','502','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (76,'Antioch','607','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (77,'Antioch','607','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (78,'Antioch','607','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (79,'Antioch','604','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (80,'Antioch','604','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (81,'Antioch','604','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (82,'Antioch','605','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (83,'Antioch','605','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (84,'Antioch','605','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (85,'Antioch','603','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (86,'Antioch','603','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (87,'Antioch','603','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (88,'Antioch','608','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (89,'Antioch','611','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (90,'Antioch','611','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (91,'Antioch','611','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (92,'Antioch','P705','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (93,'Antioch','P705','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (94,'Antioch','P701','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (95,'Antioch','P701','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (96,'Antioch','P702','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (97,'Antioch','P702','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (98,'Antioch','P702','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (99,'Antioch','P704','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (100,'Antioch','P704','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (101,'Antioch','608','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (102,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (103,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (104,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (105,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (106,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (107,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (108,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (109,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (110,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (111,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (112,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (113,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (114,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (115,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (116,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (117,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (118,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (119,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (120,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (121,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (122,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (123,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (124,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (125,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (126,'Crestview','Iron Man Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (127,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (128,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (129,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (130,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (131,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (132,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (133,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (134,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (135,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (136,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (137,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (138,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (139,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (140,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (141,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (142,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (143,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (144,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (145,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (146,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (147,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (148,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (149,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (150,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (151,'Crestview','Hawkeye Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (152,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (153,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (154,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (155,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (156,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (157,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (158,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (159,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (160,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (161,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (162,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (163,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (164,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (165,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (166,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (167,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (168,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (169,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (170,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (171,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (172,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (173,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (174,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (175,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (176,'Crestview','Black Widow Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (177,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (178,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (179,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (180,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (181,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (182,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (183,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (184,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (185,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (186,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (187,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (188,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (189,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (190,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (191,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (192,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (193,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (194,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (195,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (196,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (197,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (198,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (199,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (200,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (201,'Crestview','Hulk Cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (202,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (203,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (204,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (205,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (206,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (207,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (208,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (209,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (210,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (211,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (212,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (213,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (214,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (215,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (216,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (217,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (218,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (219,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (220,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (221,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (222,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (223,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (224,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (225,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (226,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (227,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (228,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (229,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (230,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (231,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (232,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (233,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (234,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (235,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (236,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (237,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (238,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (239,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (240,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (241,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (242,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (243,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (244,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (245,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (246,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (247,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (248,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (249,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (250,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (251,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (252,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (253,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (254,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (255,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (256,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (257,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (258,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (259,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (260,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (261,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (262,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (263,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (264,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (265,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (266,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (267,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (268,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (269,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (270,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (271,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (272,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (273,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (274,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (275,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (276,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (277,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (278,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (279,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (280,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (281,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (282,'Crestview','813','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (283,'Crestview','MC','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (284,'Crestview','Girls Softball','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (285,'Crestview','103','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (286,'Crestview','103','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (287,'Crestview','105','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (288,'Crestview','105','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (289,'Crestview','113','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (290,'Crestview','113','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (291,'Crestview','117','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (292,'Crestview','117','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (293,'Crestview','141','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (294,'Crestview','145','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (295,'Crestview','149','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (296,'Crestview','149','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (297,'Crestview','151','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (298,'Crestview','151','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (299,'Crestview','247','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (300,'Crestview','247','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (301,'Crestview','141','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (302,'Crestview','145','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (303,'Crestview','342','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (304,'Crestview','342','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (305,'Crestview','344','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (306,'Crestview','344','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (307,'Crestview','361','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (308,'Crestview','361','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (309,'Crestview','402','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (310,'Crestview','402','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (311,'Crestview','406','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (312,'Crestview','406','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (313,'Crestview','409','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (314,'Crestview','409','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (315,'Crestview','410','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (316,'Crestview','410','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (317,'Crestview','411','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (318,'Crestview','411','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (319,'Crestview','412','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (320,'Crestview','412','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (321,'Crestview','502','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (322,'Crestview','502','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (323,'Crestview','506','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (324,'Crestview','506','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (325,'Crestview','513','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (326,'Crestview','513','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (327,'Crestview','601','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (328,'Crestview','601','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (329,'Crestview','820','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (330,'Crestview','820','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (331,'Crestview','821','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (332,'Crestview','821','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (333,'Crestview','822','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (334,'Crestview','822','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (335,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (336,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (337,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (338,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (339,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (340,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (341,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (342,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (343,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (344,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (345,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (346,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (347,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (348,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (349,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (350,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (351,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (352,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (353,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (354,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (355,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (356,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (357,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (358,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (359,'Crestview','Captain America cart','CB',NULL);
INSERT INTO arrg_PLACEMENT VALUES (360,'Crestview','503','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (361,'Crestview','503','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (362,'Crestview','503','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (363,'Crestview','348','DT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (364,'Crestview','410','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (365,'Crestview','410','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (366,'Crestview','410','LT',NULL);
INSERT INTO arrg_PLACEMENT VALUES (367,'Bob Sikes','12Lab','DT','FQGLR52');
INSERT INTO arrg_PLACEMENT VALUES (368,'Bob Sikes','12Lab','DT','F5WJR52');
INSERT INTO arrg_PLACEMENT VALUES (369,'Bob Sikes','12Lab','DT','FQHLR52');
INSERT INTO arrg_PLACEMENT VALUES (370,'Bob Sikes','12Lab','DT','FQHMR52');
INSERT INTO arrg_PLACEMENT VALUES (371,'Bob Sikes','12Lab','DT','F5TMR52');
INSERT INTO arrg_PLACEMENT VALUES (372,'Bob Sikes','12Lab','DT','F5SKR52');
INSERT INTO arrg_PLACEMENT VALUES (373,'Bob Sikes','12Lab','DT','F5RMR52');
INSERT INTO arrg_PLACEMENT VALUES (374,'Bob Sikes','12Lab','DT','F5WKR52');
INSERT INTO arrg_PLACEMENT VALUES (375,'Bob Sikes','12Lab','DT','F5SLR52');
INSERT INTO arrg_PLACEMENT VALUES (376,'Bob Sikes','12Lab','DT','F5VLR52');
INSERT INTO arrg_PLACEMENT VALUES (377,'Bob Sikes','12Lab','DT','F5TKR52');
INSERT INTO arrg_PLACEMENT VALUES (378,'Bob Sikes','12Lab','DT','FQJLR52');
INSERT INTO arrg_PLACEMENT VALUES (379,'Bob Sikes','12Lab','DT','F5TLR52');
INSERT INTO arrg_PLACEMENT VALUES (380,'Bob Sikes','12Lab','DT','F5SMR52');
INSERT INTO arrg_PLACEMENT VALUES (381,'Bob Sikes','12Lab','DT','F5RLR52');
INSERT INTO arrg_PLACEMENT VALUES (382,'Bob Sikes','12Lab','DT','F5VKR52');
INSERT INTO arrg_PLACEMENT VALUES (383,'Bob Sikes','12Lab','DT','FQJKR52');
INSERT INTO arrg_PLACEMENT VALUES (384,'Bob Sikes','12Lab','DT','FQHKR52');
INSERT INTO arrg_PLACEMENT VALUES (385,'Bob Sikes','12Lab','DT','F5TJR52');
INSERT INTO arrg_PLACEMENT VALUES (386,'Bob Sikes','12Lab','DT','F5VJR52');
INSERT INTO arrg_PLACEMENT VALUES (387,'Bob Sikes','12Lab','DT','FQGMR52');
INSERT INTO arrg_PLACEMENT VALUES (388,'Bob Sikes','12Lab','DT','F5VMR52');
INSERT INTO arrg_PLACEMENT VALUES (389,'Bob Sikes','12Lab','DT','F5SJR52');
INSERT INTO arrg_PLACEMENT VALUES (390,'Bob Sikes','6','CB','5H2V952');
INSERT INTO arrg_PLACEMENT VALUES (391,'Bob Sikes','6','CB','7N2V952');
INSERT INTO arrg_PLACEMENT VALUES (392,'Bob Sikes','6','CB','9X2V952');
INSERT INTO arrg_PLACEMENT VALUES (393,'Bob Sikes','7','CB','F52V952');
INSERT INTO arrg_PLACEMENT VALUES (394,'Bob Sikes','7','CB','BT2V952');
INSERT INTO arrg_PLACEMENT VALUES (395,'Bob Sikes','7','CB','4W2V952');
INSERT INTO arrg_PLACEMENT VALUES (396,'Bob Sikes','35','CB','48QT952');
INSERT INTO arrg_PLACEMENT VALUES (397,'Bob Sikes','35','CB','9V2V952');
INSERT INTO arrg_PLACEMENT VALUES (398,'Bob Sikes','35','CB','728T952');
INSERT INTO arrg_PLACEMENT VALUES (399,'Bob Sikes','36','CB','8M2V952');
INSERT INTO arrg_PLACEMENT VALUES (400,'Bob Sikes','36','CB','FQ2V952');
INSERT INTO arrg_PLACEMENT VALUES (401,'Bob Sikes','36','CB','4D2V952');
INSERT INTO arrg_PLACEMENT VALUES (402,'Bob Sikes','37','CB','3R2V952');
INSERT INTO arrg_PLACEMENT VALUES (403,'Bob Sikes','37','CB','3T2V952');
INSERT INTO arrg_PLACEMENT VALUES (404,'Bob Sikes','37','CB','FN2V952');
INSERT INTO arrg_PLACEMENT VALUES (405,'Bob Sikes','38','CB','2P2V952');
INSERT INTO arrg_PLACEMENT VALUES (406,'Bob Sikes','38','CB','3P2V952');
INSERT INTO arrg_PLACEMENT VALUES (407,'Bob Sikes','38','CB','8T2V952');
INSERT INTO arrg_PLACEMENT VALUES (408,'Bob Sikes','45','CB','BQ2V952');
INSERT INTO arrg_PLACEMENT VALUES (409,'Bob Sikes','45','CB','6B2V952');
INSERT INTO arrg_PLACEMENT VALUES (410,'Bob Sikes','45','CB','6V2V952');
INSERT INTO arrg_PLACEMENT VALUES (411,'Bob Sikes','57','CB','FP1V952');
INSERT INTO arrg_PLACEMENT VALUES (412,'Bob Sikes','8','LT','B7SPH12');
INSERT INTO arrg_PLACEMENT VALUES (413,'Bob Sikes','8','LT','6TRPH12');
INSERT INTO arrg_PLACEMENT VALUES (414,'Bob Sikes','8','LT','1SSPH12');
INSERT INTO arrg_PLACEMENT VALUES (415,'Bob Sikes','8','LT','C5SPH12');
INSERT INTO arrg_PLACEMENT VALUES (416,'Bob Sikes','9','LT','HQRPH12');
INSERT INTO arrg_PLACEMENT VALUES (417,'Bob Sikes','9','LT','GBSPH12');
INSERT INTO arrg_PLACEMENT VALUES (418,'Bob Sikes','9','LT','1RSPH12');
INSERT INTO arrg_PLACEMENT VALUES (419,'Bob Sikes','10','LT','8JSPH12');
INSERT INTO arrg_PLACEMENT VALUES (420,'Bob Sikes','10','LT','CQMPH12');
INSERT INTO arrg_PLACEMENT VALUES (421,'Bob Sikes','10','LT','66SPH12');
INSERT INTO arrg_PLACEMENT VALUES (422,'Bob Sikes','13','LT','FNSPH12');
INSERT INTO arrg_PLACEMENT VALUES (423,'Bob Sikes','15','LT','F5VPH12');
INSERT INTO arrg_PLACEMENT VALUES (424,'Bob Sikes','15','LT','FMRPH12');
INSERT INTO arrg_PLACEMENT VALUES (425,'Bob Sikes','15','LT','47TPH12');
INSERT INTO arrg_PLACEMENT VALUES (426,'Bob Sikes','16','LT','JQMPH12');
INSERT INTO arrg_PLACEMENT VALUES (427,'Bob Sikes','16','LT','73SPH12');
INSERT INTO arrg_PLACEMENT VALUES (428,'Bob Sikes','19','LT','DVSPH12');
INSERT INTO arrg_PLACEMENT VALUES (429,'Bob Sikes','19','LT','FRSPH12');
INSERT INTO arrg_PLACEMENT VALUES (430,'Bob Sikes','19','LT','8ZRPH12');
INSERT INTO arrg_PLACEMENT VALUES (431,'Bob Sikes','23','LT','JLRPH12');
INSERT INTO arrg_PLACEMENT VALUES (432,'Bob Sikes','23','LT','5F4VS32');
INSERT INTO arrg_PLACEMENT VALUES (433,'Bob Sikes','23','LT','FJ4VS32');
INSERT INTO arrg_PLACEMENT VALUES (434,'Bob Sikes','71','LT','JM4VS32');
INSERT INTO arrg_PLACEMENT VALUES (435,'Bob Sikes','71','LT','6N4VS32');
INSERT INTO arrg_PLACEMENT VALUES (436,'Bob Sikes','71','LT','33VVS32');
INSERT INTO arrg_PLACEMENT VALUES (437,'Bob Sikes','81','LT','4H0WS32');
INSERT INTO arrg_PLACEMENT VALUES (438,'Bob Sikes','81','LT','4K1QS32');
INSERT INTO arrg_PLACEMENT VALUES (439,'Bob Sikes','81','LT','70BVS32');
INSERT INTO arrg_PLACEMENT VALUES (440,'Bob Sikes','82','LT','CT8NS32');
INSERT INTO arrg_PLACEMENT VALUES (441,'Bob Sikes','82','LT','9X9VS32');
INSERT INTO arrg_PLACEMENT VALUES (442,'Bob Sikes','82','LT','7M4VS32');
INSERT INTO arrg_PLACEMENT VALUES (443,'Bob Sikes','83','LT','3N4VS32');
INSERT INTO arrg_PLACEMENT VALUES (444,'Bob Sikes','83','LT','F0BVS32');
INSERT INTO arrg_PLACEMENT VALUES (445,'Bob Sikes','83','LT','BPZTS32');
INSERT INTO arrg_PLACEMENT VALUES (446,'Bob Sikes','84','LT','2RZTS32');
INSERT INTO arrg_PLACEMENT VALUES (447,'Bob Sikes','84','LT','CJGNS32');
INSERT INTO arrg_PLACEMENT VALUES (448,'Bob Sikes','84','LT','4S8NS32');
INSERT INTO arrg_PLACEMENT VALUES (449,'Bob Sikes','86','LT','DB4VS32');
INSERT INTO arrg_PLACEMENT VALUES (450,'Bob Sikes','86','LT','1L0WS32');
INSERT INTO arrg_PLACEMENT VALUES (451,'Bob Sikes','87','LT','BJ4VS32');
INSERT INTO arrg_PLACEMENT VALUES (452,'Bob Sikes','87','LT','8FHVS32');
INSERT INTO arrg_PLACEMENT VALUES (453,'Bob Sikes','87','LT','DC4VS32');
INSERT INTO arrg_PLACEMENT VALUES (454,'Bob Sikes','88','LT','DV8NS32');
INSERT INTO arrg_PLACEMENT VALUES (455,'Bob Sikes','88','LT','4Y9VS32');
INSERT INTO arrg_PLACEMENT VALUES (456,'Bob Sikes','88','LT','JC4VS32');
INSERT INTO arrg_PLACEMENT VALUES (457,'Bob Sikes','88','LT','CZ8NS32');
INSERT INTO arrg_PLACEMENT VALUES (458,'Bob Sikes','P6','LT','62VVS32');
INSERT INTO arrg_PLACEMENT VALUES (459,'Bob Sikes','Spike Jr Cart','CB','FF2V952');
INSERT INTO arrg_PLACEMENT VALUES (460,'Bob Sikes','Spike Jr Cart','CB','2F2V952');
INSERT INTO arrg_PLACEMENT VALUES (461,'Bob Sikes','Spike Jr Cart','CB','1W2V952');
INSERT INTO arrg_PLACEMENT VALUES (462,'Bob Sikes','Spike Jr Cart','CB','5R2V952');
INSERT INTO arrg_PLACEMENT VALUES (463,'Bob Sikes','Spike Jr Cart','CB','7T2V952');
INSERT INTO arrg_PLACEMENT VALUES (464,'Bob Sikes','Spike Jr Cart','CB','BK2V952');
INSERT INTO arrg_PLACEMENT VALUES (465,'Bob Sikes','Spike Jr Cart','CB','7B2V952');
INSERT INTO arrg_PLACEMENT VALUES (466,'Bob Sikes','Spike Jr Cart','CB','DV2V952');
INSERT INTO arrg_PLACEMENT VALUES (467,'Bob Sikes','Spike Jr Cart','CB','BM2V952');
INSERT INTO arrg_PLACEMENT VALUES (468,'Bob Sikes','Spike Jr Cart','CB','5N2V952');
INSERT INTO arrg_PLACEMENT VALUES (469,'Bob Sikes','Spike Jr Cart','CB','5V2V952');
INSERT INTO arrg_PLACEMENT VALUES (470,'Bob Sikes','Spike Jr Cart','CB','HD2V952');
INSERT INTO arrg_PLACEMENT VALUES (471,'Bob Sikes','Spike Jr Cart','CB','CK2V952');
INSERT INTO arrg_PLACEMENT VALUES (472,'Bob Sikes','Spike Jr Cart','CB','7M2V952');
INSERT INTO arrg_PLACEMENT VALUES (473,'Bob Sikes','Spike Jr Cart','CB','B72V952');
INSERT INTO arrg_PLACEMENT VALUES (474,'Bob Sikes','Spike Jr Cart','CB','7K2V952');
INSERT INTO arrg_PLACEMENT VALUES (475,'Bob Sikes','Spike Jr Cart','CB','1S2V952');
INSERT INTO arrg_PLACEMENT VALUES (476,'Bob Sikes','Spike Jr Cart','CB','DJ2V952');
INSERT INTO arrg_PLACEMENT VALUES (477,'Bob Sikes','Spike Jr Cart','CB','C82V952');
INSERT INTO arrg_PLACEMENT VALUES (478,'Bob Sikes','Spike Jr Cart','CB','FJ2V952');
INSERT INTO arrg_PLACEMENT VALUES (479,'Bob Sikes','Spike Jr Cart','CB','GK2V952');
INSERT INTO arrg_PLACEMENT VALUES (480,'Bob Sikes','Spike Jr Cart','CB','3M2V952');
INSERT INTO arrg_PLACEMENT VALUES (481,'Bob Sikes','Needs a home','LT','DT8NS32');
INSERT INTO arrg_PLACEMENT VALUES (482,'Bob Sikes','Needs a home','LT','1T8NS32');
INSERT INTO arrg_PLACEMENT VALUES (483,'Bob Sikes','Needs a home','LT','CMZTS32');
INSERT INTO arrg_PLACEMENT VALUES (484,'Bob Sikes','Needs a home','LT','DS8NS32');
INSERT INTO arrg_PLACEMENT VALUES (485,'Bob Sikes','Needs a home','LT','HFHVS32');
INSERT INTO arrg_PLACEMENT VALUES (486,'Davidson','100','CB','DQDR952');
INSERT INTO arrg_PLACEMENT VALUES (487,'Davidson','201','CB','20MQ952');
INSERT INTO arrg_PLACEMENT VALUES (488,'Davidson','201','CB','FLDR952');
INSERT INTO arrg_PLACEMENT VALUES (489,'Davidson','201','CB','2NDR952');
INSERT INTO arrg_PLACEMENT VALUES (490,'Davidson','201','CB','JNDR952');
INSERT INTO arrg_PLACEMENT VALUES (491,'Davidson','201','CB','7NDR952');
INSERT INTO arrg_PLACEMENT VALUES (492,'Davidson','205','CB','4PDR952');
INSERT INTO arrg_PLACEMENT VALUES (493,'Davidson','207','CB','BMDR952');
INSERT INTO arrg_PLACEMENT VALUES (494,'Davidson','207','CB','JRCR952');
INSERT INTO arrg_PLACEMENT VALUES (495,'Davidson','300','CB','93MQ952');
INSERT INTO arrg_PLACEMENT VALUES (496,'Davidson','315','CB','BKDR952');
INSERT INTO arrg_PLACEMENT VALUES (497,'Davidson','315','CB','9KDR952');
INSERT INTO arrg_PLACEMENT VALUES (498,'Davidson','315','CB','H1NQ952');
INSERT INTO arrg_PLACEMENT VALUES (499,'Davidson','401','CB','GJDR952');
INSERT INTO arrg_PLACEMENT VALUES (500,'Davidson','403','CB','JBZP952');
INSERT INTO arrg_PLACEMENT VALUES (501,'Davidson','403','CB','3KDR952');
INSERT INTO arrg_PLACEMENT VALUES (502,'Davidson','403','CB','FHDR952');
INSERT INTO arrg_PLACEMENT VALUES (503,'Davidson','501','CB','DLDR952');
INSERT INTO arrg_PLACEMENT VALUES (504,'Davidson','503','CB','41MQ952');
INSERT INTO arrg_PLACEMENT VALUES (505,'Davidson','512','CB','GHDR952');
INSERT INTO arrg_PLACEMENT VALUES (506,'Davidson','513','CB','430Q952');
INSERT INTO arrg_PLACEMENT VALUES (507,'Davidson','513','CB','740Q952');
INSERT INTO arrg_PLACEMENT VALUES (508,'Davidson','514','CB','6JDR952');
INSERT INTO arrg_PLACEMENT VALUES (509,'Davidson','514','CB','1LDR952');
INSERT INTO arrg_PLACEMENT VALUES (510,'Davidson','515','CB','2RDR952');
INSERT INTO arrg_PLACEMENT VALUES (511,'Davidson','601','CB','2ZM7B52');
INSERT INTO arrg_PLACEMENT VALUES (512,'Davidson','603','CB','GNZP952');
INSERT INTO arrg_PLACEMENT VALUES (513,'Davidson','605','CB','870Q952');
INSERT INTO arrg_PLACEMENT VALUES (514,'Davidson','605','CB','C80Q952');
INSERT INTO arrg_PLACEMENT VALUES (515,'Davidson','606','CB','8B0Q952');
INSERT INTO arrg_PLACEMENT VALUES (516,'Davidson','606','CB','74ZP952');
INSERT INTO arrg_PLACEMENT VALUES (517,'Davidson','609','CB','D40Q952');
INSERT INTO arrg_PLACEMENT VALUES (518,'Davidson','613','CB','D80Q952');
INSERT INTO arrg_PLACEMENT VALUES (519,'Davidson','613','CB','B80Q952');
INSERT INTO arrg_PLACEMENT VALUES (520,'Davidson','614','CB','B8ZP952');
INSERT INTO arrg_PLACEMENT VALUES (521,'Davidson','700','CB','6C0Q952');
INSERT INTO arrg_PLACEMENT VALUES (522,'Davidson','700','CB','HPDR952');
INSERT INTO arrg_PLACEMENT VALUES (523,'Davidson','701','CB','260Q952');
INSERT INTO arrg_PLACEMENT VALUES (524,'Davidson','701','CB','C40Q952');
INSERT INTO arrg_PLACEMENT VALUES (525,'Davidson','701','CB','HPCR952');
INSERT INTO arrg_PLACEMENT VALUES (526,'Davidson','702','CB','6NDR952');
INSERT INTO arrg_PLACEMENT VALUES (527,'Davidson','703','CB','920Q952');
INSERT INTO arrg_PLACEMENT VALUES (528,'Davidson','703','CB','D50Q952');
INSERT INTO arrg_PLACEMENT VALUES (529,'Davidson','703','CB','D30Q952');
INSERT INTO arrg_PLACEMENT VALUES (530,'Davidson','706','CB','DRCR952');
INSERT INTO arrg_PLACEMENT VALUES (531,'Davidson','706','CB','87MQ952');
INSERT INTO arrg_PLACEMENT VALUES (532,'Davidson','707','CB','G5MQ952');
INSERT INTO arrg_PLACEMENT VALUES (533,'Davidson','708','CB','3CMQ952');
INSERT INTO arrg_PLACEMENT VALUES (534,'Davidson','709','CB','JBNQ952');
INSERT INTO arrg_PLACEMENT VALUES (535,'Davidson','Cart 1','CB','7LDR952');
INSERT INTO arrg_PLACEMENT VALUES (536,'Davidson','Cart 1','CB','J3CR952');
INSERT INTO arrg_PLACEMENT VALUES (537,'Davidson','Cart 1','CB','F70Q952');
INSERT INTO arrg_PLACEMENT VALUES (538,'Davidson','Cart 1','CB','6DCR952');
INSERT INTO arrg_PLACEMENT VALUES (539,'Davidson','Cart 1','CB','6PDR952');
INSERT INTO arrg_PLACEMENT VALUES (540,'Davidson','Cart 1','CB','4QM7B52');
INSERT INTO arrg_PLACEMENT VALUES (541,'Davidson','Cart 1','CB','J3DR952');
INSERT INTO arrg_PLACEMENT VALUES (542,'Davidson','Cart 1','CB','780Q952');
INSERT INTO arrg_PLACEMENT VALUES (543,'Davidson','Cart 1','CB','F4NQ952');
INSERT INTO arrg_PLACEMENT VALUES (544,'Davidson','Cart 1','CB','G3DR952');
INSERT INTO arrg_PLACEMENT VALUES (545,'Davidson','Cart 1','CB','G50Q952');
INSERT INTO arrg_PLACEMENT VALUES (546,'Davidson','Cart 1','CB','620Q952');
INSERT INTO arrg_PLACEMENT VALUES (547,'Davidson','Cart 1','CB','C7ZP952');
INSERT INTO arrg_PLACEMENT VALUES (548,'Davidson','Cart 1','CB','9HZP952');
INSERT INTO arrg_PLACEMENT VALUES (549,'Davidson','Cart 1','CB','G40Q952');
INSERT INTO arrg_PLACEMENT VALUES (550,'Davidson','Cart 1','CB','9FCR952');
INSERT INTO arrg_PLACEMENT VALUES (551,'Davidson','Cart 1','CB','B70Q952');
INSERT INTO arrg_PLACEMENT VALUES (552,'Davidson','Cart 1','CB','HMDR952');
INSERT INTO arrg_PLACEMENT VALUES (553,'Davidson','Cart 1','CB','F20Q952');
INSERT INTO arrg_PLACEMENT VALUES (554,'Davidson','Cart 1','CB','9JDR952');
INSERT INTO arrg_PLACEMENT VALUES (555,'Davidson','Cart 1','CB','G00Q952');
INSERT INTO arrg_PLACEMENT VALUES (556,'Davidson','Cart 1','CB','BVLQ952');
INSERT INTO arrg_PLACEMENT VALUES (557,'Davidson','Cart 1','CB','G20Q952');
INSERT INTO arrg_PLACEMENT VALUES (558,'Davidson','Cart 1','CB','3MDR952');
INSERT INTO arrg_PLACEMENT VALUES (559,'Davidson','Cart 2','CB','1B0Q952');
INSERT INTO arrg_PLACEMENT VALUES (560,'Davidson','Cart 2','CB','23ZP952');
INSERT INTO arrg_PLACEMENT VALUES (561,'Davidson','Cart 2','CB','D70Q952');
INSERT INTO arrg_PLACEMENT VALUES (562,'Davidson','Cart 2','CB','G90Q952');
INSERT INTO arrg_PLACEMENT VALUES (563,'Davidson','Cart 2','CB','CB0Q952');
INSERT INTO arrg_PLACEMENT VALUES (564,'Davidson','Cart 2','CB','490Q952');
INSERT INTO arrg_PLACEMENT VALUES (565,'Davidson','Cart 2','CB','7B0Q952');
INSERT INTO arrg_PLACEMENT VALUES (566,'Davidson','Cart 2','CB','C90Q952');
INSERT INTO arrg_PLACEMENT VALUES (567,'Davidson','Cart 2','CB','JB0Q952');
INSERT INTO arrg_PLACEMENT VALUES (568,'Davidson','Cart 2','CB','130Q952');
INSERT INTO arrg_PLACEMENT VALUES (569,'Davidson','Cart 2','CB','7TM7B52');
INSERT INTO arrg_PLACEMENT VALUES (570,'Davidson','Cart 2','CB','J40Q952');
INSERT INTO arrg_PLACEMENT VALUES (571,'Davidson','Cart 2','CB','DKDR952');
INSERT INTO arrg_PLACEMENT VALUES (572,'Davidson','Cart 2','CB','9QDR952');
INSERT INTO arrg_PLACEMENT VALUES (573,'Davidson','Cart 2','CB','FMDR952');
INSERT INTO arrg_PLACEMENT VALUES (574,'Davidson','Cart 2','CB','H40Q952');
INSERT INTO arrg_PLACEMENT VALUES (575,'Davidson','Cart 2','CB','2B0Q952');
INSERT INTO arrg_PLACEMENT VALUES (576,'Davidson','Cart 2','CB','3KNR952');
INSERT INTO arrg_PLACEMENT VALUES (577,'Davidson','Cart 2','CB','CHM7B52');
INSERT INTO arrg_PLACEMENT VALUES (578,'Davidson','Cart 2','CB','C30Q952');
INSERT INTO arrg_PLACEMENT VALUES (579,'Davidson','Cart 2','CB','84NQ952');
INSERT INTO arrg_PLACEMENT VALUES (580,'Davidson','Cart 2','CB','CMRP952');
INSERT INTO arrg_PLACEMENT VALUES (581,'Davidson','Cart 2','CB','360Q952');
INSERT INTO arrg_PLACEMENT VALUES (582,'Davidson','Cart 2','CB','H20Q952');
INSERT INTO arrg_PLACEMENT VALUES (583,'Davidson','508-ISS','LT','5GGNS32');
INSERT INTO arrg_PLACEMENT VALUES (584,'Davidson','MC','LT','1HDKS32');
INSERT INTO arrg_PLACEMENT VALUES (585,'Davidson','MC','LT','BV6KS32');
INSERT INTO arrg_PLACEMENT VALUES (586,'Davidson','MC','LT','JCRKS32');
INSERT INTO arrg_PLACEMENT VALUES (587,'Davidson','MC','LT','1X6KS32');
INSERT INTO arrg_PLACEMENT VALUES (588,'Davidson','MC','LT','1KXSS32');
INSERT INTO arrg_PLACEMENT VALUES (589,'Davidson','MC','LT','GXKKS32');
INSERT INTO arrg_PLACEMENT VALUES (590,'Davidson','MC','LT','1V6KS32');
INSERT INTO arrg_PLACEMENT VALUES (591,'Davidson','MC','LT','2TKKS32');
INSERT INTO arrg_PLACEMENT VALUES (592,'Davidson','MC','LT','39DKS32');
INSERT INTO arrg_PLACEMENT VALUES (593,'Davidson','MC','LT','BC1KS32');
INSERT INTO arrg_PLACEMENT VALUES (594,'Davidson','MC','LT','DVKKS32');
INSERT INTO arrg_PLACEMENT VALUES (595,'Davidson','MC','LT','66RKS32');
INSERT INTO arrg_PLACEMENT VALUES (596,'Davidson','MC','LT','CGXSS32');
INSERT INTO arrg_PLACEMENT VALUES (597,'Davidson','MC','LT','2X6KS32');
INSERT INTO arrg_PLACEMENT VALUES (598,'Davidson','MC','LT','GFXSS32');
INSERT INTO arrg_PLACEMENT VALUES (599,'Davidson','MC','LT','17RKS32');
INSERT INTO arrg_PLACEMENT VALUES (600,'Davidson','MC','LT','BD1KS32');
INSERT INTO arrg_PLACEMENT VALUES (601,'Davidson','MC','LT','BHXSS32');
INSERT INTO arrg_PLACEMENT VALUES (602,'Davidson','MC','LT','6Y6KS32');
INSERT INTO arrg_PLACEMENT VALUES (603,'Davidson','MC','LT','32YKS32');
INSERT INTO arrg_PLACEMENT VALUES (604,'Davidson','MC','DT','F5NJR52');
INSERT INTO arrg_PLACEMENT VALUES (605,'Davidson','MC','DT','F5LKR52');
INSERT INTO arrg_PLACEMENT VALUES (606,'Davidson','MC','DT','F5NMR52');
INSERT INTO arrg_PLACEMENT VALUES (607,'Davidson','MC','DT','F5KLR52');
INSERT INTO arrg_PLACEMENT VALUES (608,'Davidson','MC','DT','F5NLR52');
INSERT INTO arrg_PLACEMENT VALUES (609,'Davidson','MC','DT','F5KMR52');
INSERT INTO arrg_PLACEMENT VALUES (610,'Davidson','MC','DT','F5JKR52');
INSERT INTO arrg_PLACEMENT VALUES (611,'Davidson','MC','DT','F5MLR52');
INSERT INTO arrg_PLACEMENT VALUES (612,'Davidson','MC','DT','F5KKR52');
INSERT INTO arrg_PLACEMENT VALUES (613,'Davidson','MC','DT','F5HMR52');
INSERT INTO arrg_PLACEMENT VALUES (614,'Davidson','MC','DT','F5MMR52');
INSERT INTO arrg_PLACEMENT VALUES (615,'Davidson','MC','DT','F5JMR52');
INSERT INTO arrg_PLACEMENT VALUES (616,'Davidson','MC','DT','F5MKR52');
INSERT INTO arrg_PLACEMENT VALUES (617,'Davidson','MC','DT','F5LLR52');
INSERT INTO arrg_PLACEMENT VALUES (618,'Davidson','Circulation','DT','F5JLR52');
INSERT INTO arrg_PLACEMENT VALUES (619,'Davidson','Needs a home','CB','8KDR952');
INSERT INTO arrg_PLACEMENT VALUES (620,'Davidson','Needs a home','CB','250Q952');
INSERT INTO arrg_PLACEMENT VALUES (621,'Davidson','Needs a home','CB','850Q952');
INSERT INTO arrg_PLACEMENT VALUES (622,'Davidson','Needs a home','DT','F5NKR52');
INSERT INTO arrg_PLACEMENT VALUES (623,'Davidson','Needs a home','DT','F5LMR52');

/* DO NOT RUN. this is to ensure all the tables were created correctly */
SELECT  `TABLE_NAME`,`COLUMN_NAME`,`DATA_TYPE`,`COLUMN_KEY`,`COLLATION_NAME` FROM  `COLUMNS` WHERE  `TABLE_NAME`  LIKE  'arrg%';
